/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

export * from "./collections/default-collection.generated"
export * from "./languages/english-en-us-language.generated"
export * from "./languages/german-de-de-language.generated"
export * from "./languages/spanish-es-es-language.generated"
export * from "./snippets/metadata.generated"
export * from "./system/collections.generated"
export * from "./system/elements.generated"
export * from "./system/languages.generated"
export * from "./system/main.system.generated"
export * from "./system/snippets.generated"
export * from "./system/taxonomies.generated"
export * from "./system/types.generated"
export * from "./system/workflows.generated"
export * from "./taxonomies/article-type.generated"
export * from "./taxonomies/event-topic.generated"
export * from "./taxonomies/event-type.generated"
export * from "./taxonomies/general-healthcare-topics.generated"
export * from "./taxonomies/medical-specialties.generated"
export * from "./types/article.generated"
export * from "./types/blog-post.generated"
export * from "./types/call-to-action.generated"
export * from "./types/disclaimer.generated"
export * from "./types/event.generated"
export * from "./types/landing-page.generated"
export * from "./types/page.generated"
export * from "./types/person.generated"
export * from "./types/service.generated"
export * from "./types/video.generated"
export * from "./workflows/default-workflow.generated"
