/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.1'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Karma Health Demo
 * Environment: Karma Health - IvanK
 * Id: ed845612-1d5a-018a-110d-81ee1eee30bf
 * 
 * -------------------------------------------------------------------------------
 */

import type { ArticleType } from "../types/article.generated"
import type { BlogPostType } from "../types/blog-post.generated"
import type { CallToActionType } from "../types/call-to-action.generated"
import type { DisclaimerType } from "../types/disclaimer.generated"
import type { EventType } from "../types/event.generated"
import type { LandingPageType } from "../types/landing-page.generated"
import type { PageType } from "../types/page.generated"
import type { PersonType } from "../types/person.generated"
import type { ServiceType } from "../types/service.generated"
import type { VideoType } from "../types/video.generated"

/*
 * Array of all type codenames
 */
export const typeCodenames = [
  "blog_post",
  "landing_page",
  "service",
  "call_to_action",
  "page",
  "event",
  "person",
  "video",
  "disclaimer",
  "article",
] as const

/*
 * Type representing all type codenames
 */
export type TypeCodenames = (typeof typeCodenames)[number]

/*
 * Typeguard for type codename
 */
export function isTypeCodename(value: string | undefined | null): value is TypeCodenames {
  return typeof value === "string" && (typeCodenames as readonly string[]).includes(value)
}

/*
 * Core content type with narrowed types. Use this instead of'IContentItem' for increased type safety.
 */
export type CoreType =
  | BlogPostType
  | LandingPageType
  | ServiceType
  | CallToActionType
  | PageType
  | EventType
  | PersonType
  | VideoType
  | DisclaimerType
  | ArticleType

/*
 * Type mapping for codename & type. Can be used for type safe access to type based on the codename of type.
 */
export type CodenameTypeMapping = {
  readonly blog_post: BlogPostType
  readonly landing_page: LandingPageType
  readonly service: ServiceType
  readonly call_to_action: CallToActionType
  readonly page: PageType
  readonly event: EventType
  readonly person: PersonType
  readonly video: VideoType
  readonly disclaimer: DisclaimerType
  readonly article: ArticleType
}

/*
 * Helper type that returns type based on the codename of type.
 */
export type CodenameTypeMapper<TTypeCodename extends TypeCodenames> = TTypeCodename extends keyof CodenameTypeMapping
  ? CodenameTypeMapping[TTypeCodename]
  : CoreType
